function modelPath = build_physics_simulink_model(modelDir, modelName, A, B, C, D)
%BUILD_PHYSICS_SIMULINK_MODEL  Create a Simulink model from physics A,B,C,D.
%
% Builds: Voltage-Sag-Input → State-Space → To-Workspace
% The state-space matrices are assigned via workspace variables before sim().
%
% Usage:
%   path = build_physics_simulink_model(rootDir, 'my_model', A, B, C, D);
%   ... assign ss_A, ss_B, ss_C, ss_D, fault_input, sim_stop_time to base ...
%   out = sim(path);

if nargin < 2 || isempty(modelName)
    modelName = 'se_gfl_physics_model';
end
modelPath = fullfile(modelDir, [modelName '.slx']);

if bdIsLoaded(modelName), close_system(modelName, 0); end
if exist(modelPath, 'file'), delete(modelPath); end

new_system(modelName);
set_param(modelName, ...
    'StopTime',     'sim_stop_time', ...
    'Solver',       'ode45', ...
    'MaxStep',      '5e-4', ...
    'RelTol',       '1e-6', ...
    'SaveOutput',   'off', ...
    'SignalLogging', 'off');

% ── blocks ──────────────────────────────────────────────────────────────
add_block('simulink/Sources/From Workspace', ...
    [modelName '/Vq_Sag'], ...
    'VariableName', 'fault_input', ...
    'Position', [60 95 180 125]);

add_block('simulink/Continuous/State-Space', ...
    [modelName '/GFL_Physics'], ...
    'A', 'ss_A', 'B', 'ss_B', 'C', 'ss_C', 'D', 'ss_D', ...
    'Position', [240 75 420 145]);

add_block('simulink/Sinks/To Workspace', ...
    [modelName '/dP_out'], ...
    'VariableName', 'simout_dP', ...
    'SaveFormat',   'Structure With Time', ...
    'Position', [490 90 620 130]);

% ── wiring ───────────────────────────────────────────────────────────────
add_line(modelName, 'Vq_Sag/1',     'GFL_Physics/1', 'autorouting', 'on');
add_line(modelName, 'GFL_Physics/1', 'dP_out/1',     'autorouting', 'on');

% ── annotation: record matrix dimensions ─────────────────────────────────
note = sprintf('Physics GFL model: %d converters, %d states\nA=%dx%d  B=%dx%d  C=%dx%d', ...
    size(C,1), size(A,1), size(A,1), size(A,2), ...
    size(B,1), size(B,2), size(C,1), size(C,2));
Simulink.Annotation(modelName, note);

save_system(modelName, modelPath);
close_system(modelName, 0);
end
